#Lethal Cost
#range: 1 to 255
lethal_cost: 253
#Neutral Cost
#range: 1 to 255
neutral_cost: 50
#Factor to multiply each cost from costmap by
#range: 0.01 to 5.0
cost_factor: 3.0
#Publish Potential Costmap
#range: True to False
publish_potential: true

#How to set the orientation of each point
#range: 0 to 6
#options:
#0 = "None", No orientations added except goal orientation
#1 = "Forward", Positive x axis points along path, except for the goal orientation
#2 = "Interpolate", Orientations are a linear blend of start and goal pose
#3 = "ForwardThenInterpolate", Forward orientation until last straightaway, then a linear blend until the goal pose
#4 = "Backward", Negative x axis points along the path, except for the goal orientation
#5 = "Leftward", Positive y axis points along the path, except for the goal orientation
#6 = "Rightward", Negative y axis points along the path, except for the goal orientation
orientation_mode: 1
#What window to use to determine the orientation based on the position derivative specified by the orientation mode
#range: 1 to 255
orientation_window_size: 1

allow_unknown: true
planner_window_x: 0.0
planner_window_y: 0.0
default_tolerance: 0.0
publish_scale: 100
outline_map: true

