#The name of the plugin for the global planner to use with move_base.
#range: 
base_global_planner: "navfn/NavfnROS"
#The name of the plugin for the local planner to use with move_base.
#range: 
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

#A list of recovery behavior plugins to use with move_base.
#range: 
#recovery_behaviors: "[{
#  name: conservative_reset, 
#  type: clear_costmap_recovery/ClearCostmapRecovery}, 
#  {name: rotate_recovery, 
#  type: rotate_recovery/RotateRecovery}, 
#  {name: aggressive_reset, 
#  type: clear_costmap_recovery/ClearCostmapRecovery}]")

#The rate in Hz at which to run the planning loop.
#range: 0 to 100
planner_frequency: 0
#The rate in Hz at which to run the control loop and send velocity commands to the base.
#range: 0 to 100
controller_frequency: 20
#How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.
#range: 0 to 100
planner_patience: 5.0
#How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed.
#range: 0 to 100
#defaults to 15.0 in code but 5.0 on param server
controller_patience: 5.0
#How many times we will recall the planner in an attempt to find a valid plan before space-clearing operations are performed
#range: -1 to 1000
max_planning_retries: -1
#The distance away from the robot in meters at which obstacles will be cleared from the costmap when attempting to clear space in the map.
#range: 0 to 50
conservative_reset_dist: 3

#Whether or not to enable the move_base recovery behaviors to attempt to clear out space.
#range: True to False
recovery_behavior_enabled: true
# Doesnt exist
#Determines whether or not the robot will attempt an in-place rotation when attempting to clear out space.
#range: True to False
clearing_rotation_allowed: true
#Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state
#range: True to False
shutdown_costmaps: false

#How long in seconds to allow for oscillation before executing recovery behaviors.
#range: 0 to 60
oscillation_timeout: 0.0
#How far in meters the robot must move to be considered not to be oscillating.
#range: 0 to 10
oscillation_distance: 0.5

#parameters of make_plan service
#Whether or not to clear the global costmap on make_plan service call.
#range: True to False
make_plan_clear_costmap: true
#Whether or not to add the original goal to the path if it is unreachable in the make_plan service call.
#range: True to False
make_plan_add_unreachable_goal: true

#Restore to the original configuration
#range: True to False
restore_defaults: false

#global_costmap/robot_base_frame: "base_link"
#global_costmap/global_frame: "map"

#local_costmap/inscribed_radius: 0.325
#local_costmap/circumscribed_radius: 0.46
#clearing_radius: #equals the circumscribed_radius

